import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Nav } from "./Nav";
// import { Post } from "./Post";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav />
        {/* If we render <Post /> here the entier app will be opted in to dynamic rendering!!! */}
        {/* Since post reads from cookies it has to be dynamic */}
        {/* make sure that all components that used a dynamic api are as far below */}
        {/* the component tree as possible, (nested inside special route segments or slot ) */}
        {/* <Post postNum={1} /> */}
        <div className="px-4">{children}</div>
      </body>
    </html>
  );
}
